# -*- coding: utf-8 -*-
"""Atividade01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbCI96k6Xq9f4zitFn4SkA5TaV0fxa-F
"""

from datetime import date
# MODEL
class Client:
  def __init__(self, name:str, age:int):
    self.name = name
    self.age = age

class Doctor:
  def __init__(self, name:str, speciality:str):
    self.name = name
    self.speciality = speciality

class Appointment:
  def __init__(self, tDate:date, client:Client, doctor:Doctor, value:float, payment:bool):
    self.tDate = tDate
    self.client = client
    self.doctor = doctor
    self.value = value
    self.payment = payment

# CONTROLLER
class ClientController:
  def __init__(self):
    self.clients = []

  def addClient(self, client:Client):
    self.clients.append(client)

  def listAll(self):
    return self.clients

  def findById(self, id:int):
    if 0 <= id < len(self.clients):
      return self.clients[id]
    else:
      return -1

  def removeClient(self, id:int):
    if 0 <= id < len(self.clients):
      removed = self.clients.pop(id)
      return removed
    else:
      return -1

class DoctorController:
  def __init__(self):
    self.doctors = []

  def addDoctor(self, doctor:Doctor):
    self.doctors.append(doctor)

  def listAll(self):
    return self.doctors

  def findById(self, id:int):
    if 0 <= id < len(self.doctors):
      return self.doctors[id]
    else:
      return -1

  def removeDoctor(self, id:int):
    if 0 <= id < len(self.doctors):
      removed = self.doctors.pop(id)
      return removed
    else:
      return -1

class AppointmentController:
  def __init__(self):
    self.appointments = []

  def addAppointment(self, appointment:Appointment):
    self.appointments.append(appointment)
    print("Doctor Sucessfully Added!")

  def listAll(self):
    return self.appointments

  def removeAppointment(self, id:int):
    if 0 <= id < len(self.appointments):
      removed = self.appointments.pop(id)
      return 0
    else:
      return -1

# VIEW
class ClientView:
  def menu(self, controller:ClientController):
    while True:
      print("\n--- CLIENT'S MENU ---")
      print("1 - Add")
      print("2 - List All")
      print("3 - Search by ID")
      print("4 - Remove")
      print("5 - Exit")
      option = input("Choice: ")
      match option:
        case "1": self.addClient(controller)
        case "2": self.listAll(controller)
        case "3": self.searchById(controller)
        case "4": self.remove(controller)
        case "5":
          print("Exiting...")
          break
        case _: print("Choice Invalid!")

  def addClient(self, controller:ClientController):
    name = input("Client's Name: ")
    age = int(input("Client's Age: "))
    client = Client(name, age)
    controller.addClient(client)
    print("Client Sucessfully Added!")

  def listAll(self, controller:ClientController):
    clients = controller.listAll()
    print("\n=== Clients' List ===")
    for c, client in enumerate(clients):
      print(f"{c} - {client.name}, {client.age} years old.")
      print("---------------------------------")

  def searchById(self, controller:ClientController):
    id = int(input("Client's ID: "))
    client = controller.findById(id)
    if (client == -1):
      print("ID Invalid!")
    else:
      print("\nClient's Info:")
      print(f"Name: {client.name}")
      print(f"Age: {client.age}")

  def remove(self, controller:ClientController):
    id = int(input("Client's ID: "))
    result = controller.removeClient(id)
    if result == -1:
      print("ID Invalid!")
    else:
      print(f"Client {result.name} Removed!")

class DoctorView:
  def menu(self, controller:DoctorController):
    while True:
      print("\n--- DOCTOR'S MENU ---")
      print("1 - Add")
      print("2 - List All")
      print("3 - Search by ID")
      print("4 - Remove")
      print("5 - Exit")
      option = input("Choice: ")
      match option:
        case "1": self.add(controller)
        case "2": self.listAll(controller)
        case "3": self.searchById(controller)
        case "4": self.remove(controller)
        case "5":
          print("Exiting...")
          break
        case _: print("Choice Invalid!")

  def add(self, controller:DoctorController):
    name = input("Doctor's Name: ")
    speciality = input("Doctor's Speciality: ")
    doctor = Doctor(name, speciality)
    controller.addDoctor(doctor)
    print("Doctor Sucessfully Added!")

  def listAll(self, controller:DoctorController):
    doctors = controller.listAll()
    print("\n=== Doctors' List ===")
    for d, doctor in enumerate(doctors):
      print(f"{d} - {doctor.name}, {doctor.speciality}")
      print("---------------------------------")

  def searchById(self, controller:DoctorController):
    id = int(input("Client's ID: "))
    doctor = controller.findById(id)
    if (doctor == -1):
      print("ID Invalid!")
    else:
      print("\nDoctor's Info:")
      print(f"Name: {doctor.name}")
      print(f"Speciality: {doctor.speciality}")

  def remove(self, controller:DoctorController):
    id = int(input("Doctor's ID: "))
    result = controller.removeDoctor(id)
    if result == -1:
      print("ID Invalid!")
    else:
      print(f"Doctor {result.name} Removed!")

class AppointmentView:
  def menu(self, controller:AppointmentController, controllerC:ClientController, controllerD:DoctorController):
    while True:
      print("\n--- APPOINTMENT'S MENU ---")
      print("1 - Add")
      print("2 - List All")
      print("3 - Remove")
      print("4 - Exit")
      option = input("Choice: ")
      match option:
        case "1": self.add(controller, controllerC, controllerD)
        case "2": self.listAll(controller)
        case "3": self.remove(controller)
        case "4":
          print("Exiting...")
          break
        case _: print("Choice Invalid!")

  def add(self, controller:AppointmentController, controllerC:ClientController, controllerD:DoctorController):
    bDate = input("Appointment's Date (yyyy-mm-dd): ").split("-")
    tDate = date(year=int(bDate[0]), month=int(bDate[1]), day=int(bDate[2]))
    id = int(input("Client's ID: "))
    client = controllerC.findById(id)
    id = int(input("Doctor's ID: "))
    doctor = controllerD.findById(id)
    value = float(input("Appointment's Cost: R$"))
    payment = input("Did the Client Pay? (y or n)\n")
    if (payment.lower() == "y"):
      print("Appointment Booked!")
      print("Sending Confirmation by Email.")
      payment = True
    else:
      print("Waitting Payment...")
      payment = False
    appointment = Appointment(tDate, client, doctor, value, payment)
    controller.addAppointment(appointment)

  def listAll(self, controller:AppointmentController):
    appointments = controller.listAll()
    print("\n=== Appointments' List ===")
    for a, appointment in enumerate(appointments):
      print(f"ID: {a}")
      print(f"Date: {appointment.tDate}")
      print(f"Client: {appointment.client.name}")
      print(f"Doctor: {appointment.doctor.name}")
      print(f"Value: R$ {appointment.value:.2f}")
      print(f"Payment: {appointment.payment}")
      print("---------------------------------")

  def remove(self, controller:AppointmentController):
    id = int(input("Appointment's ID: "))
    result = controller.removeAppointment(id)
    if result == -1:
      print("ID Invalid!")
    else:
      print(f"Appointment({id}) Removed!")

# MAIN
clientController = ClientController()
doctorController = DoctorController()
appointmentController = AppointmentController()
clientView = ClientView()
doctorView = DoctorView()
appointmentView = AppointmentView()

while True:
  print("\n--- MAIN MENU ---")
  print("1 - Clients")
  print("2 - Doctors")
  print("3 - Appointments")
  print("4 - Exit")
  option = input("Choice: ")
  match option:
    case "1": clientView.menu(clientController)
    case "2": doctorView.menu(doctorController)
    case "3": appointmentView.menu(appointmentController, clientController, doctorController)
    case "4":
      print("Exiting...")
      break
    case _:
      print("Invalid Choice!")