# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hh9kXVhcIPMg5h3IHGthkYDYOk7Bmywy
"""

# MODEL
class Product:
  def __init__(self, name:str, price:float):
    self.name = name
    self.price = price

# VIEW
class ProductView:
  def show_product(self, product:Product):
    print(f"{product.name} - R$ {product.price:.2f}")

  def show_list(self, products:list):
    print("\n--- PRODUCTS' LIST ---")
    for i, product in enumerate(products):
      print(f"{i} - {product.name} - R$ {product.price:.2f}")
      print("----------------------------------")

# CONTROLLER
class ProductController:
  def __init__(self):
    self.products = []
    self.view = ProductView()

  def addProduct(self, product:Product):
    self.products.append(product)
    print("Sucessfully Product Added!")

  def listAll(self):
    self.view.show_list(self.products)

  def editProduct(self, product:Product, id:int):
    if 0 <= id < len(self.products):
      self.products[id] = product
      print(f"Product {self.products[id].name} Updated!")
    else:
      print("Invalid ID!")

  def removeProduct(self, id:int):
    if 0 <= id < len(self.products):
      removed = self.products.pop(id)
      print(f"Product {removed.name} Removed!")
    else:
      print("Invalid ID!")

# MAIN
controller = ProductController()

while True:
  print("\n--- MAIN OPTIONS ---")
  print("1 - Add")
  print("2 - List")
  print("3 - Update")
  print("4 - Remove")
  print("5 - Exit")

  option = input("Choice: ")
  match option:
    case "1":
      name = input("Product's Name: ")
      price = float(input("Price: "))
      product = Product(name, price)
      controller.addProduct(product)
    case "2":
      controller.listAll()
    case "3":
      id = int(input("ID for Update: "))
      name = input("Product's New Name: ")
      price = float(input("Price: "))
    case "3":
      id = int(input("ID for Remotion: "))
      controller.removeProduct(id)
    case "5":
      print("Exiting...")
      break
    case _:
      print("Invalid Option!")