# -*- coding: utf-8 -*-
"""Atividade 01 - 2026_02_13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIkh_VNOIApOyotx-gyz6J5Jav2Wy-SG
"""

#Group: Kaick, Arthur, J. Anderson
from datetime import date

class Patient:
  def __init__(self, cpf:str, name:str, address:str, phone:str, bloodType:str):
    self._id = cpf
    self._name = name
    self._address = address
    self._phone = phone
    self._bloodType = bloodType

  @property
  def id(self): return self._id
  @property
  def name(self): return self._name
  @property
  def address(self): return self._address
  @property
  def phone(self): return self._phone
  @property
  def bloodType(self): return self._bloodType

class Doctor:
  def __init__(self, idDoctor:str, name:str, specialty:str, phone:str):
    self._id = idDoctor
    self._name = name
    self._specialty = specialty
    self._phone = phone

  @property
  def id(self): return self._id
  @property
  def name(self): return self._name
  @property
  def specialty(self): return self._specialty
  @property
  def phone(self): return self._phone

class Appointment:
  def __init__(self, idAppointment:str, nDate:date, patient:Patient, doctor:Doctor, observations:str=""):
    self._id = idAppointment
    self._nDate = nDate
    self._patient = patient
    self._doctor = doctor
    self._observations = observations

  @property
  def id(self): return self._id
  @property
  def nDate(self): return self._nDate
  @property
  def patient(self): return self._patient
  @property
  def doctor(self): return self._doctor
  @property
  def observations(self): return self._observations

class AppointmentService:
  def __init__(self):
    self._appointments = []

  def createAppointment(self, appointment:Appointment):
    self._appointments.append(appointment)
    print(f"Appointment ({appointment.id}) Sucessfully Registered!")
    return appointment

  def listAll(self):
    print("------------------------------")
    for a in self._appointments:
      print("ID:", a.id)
      print("Date:", a.nDate)
      print("Patient:", a.patient.name)
      print("Doctor:", a.doctor.name)
      if(a.observations != ""):
        print("Observation:", a.observations)
      print("------------------------------")

p1 = Patient("11111111111", "Mary", "Whatsit Street, 24", "11 1111-1111", "Type A+")
p2 = Patient("22222222222", "John", "Elm Street, 56", "22 2222-2222", "Type AB-")
p3 = Patient("33333333333", "Steve", "BackBoys Street, 425", "33 3333-3333", "Type B+")
p4 = Patient("44444444444", "Nancy", "Garlic Street, 35", "44 4444-4444", "Type O+")
p5 = Patient("55555555555", "Mike", "Washiton Street, 1523", "55 5555-5555", "Type O-")

d1 = Doctor("D001", "Dr. Hopper", "Cardiologist", "77 7777-7777")
d2 = Doctor("D002", "Dr. Joice", "Pediatrician", "88 8888-8888")

a1 = Appointment("A001", date(2026,1,20), p1, d1)
a2 = Appointment("A002", date(2026,1,2), p2, d2, "Kid with Stomach ache.")
a3 = Appointment("A003", date(2025,9,15), p3, d1, "His Heart Stopped during the Appointment.")
a4 = Appointment("A004", date(2025,6,4), p4, d2)
a5 = Appointment("A005", date(2025,12,18), p5, d1)

service = AppointmentService()
service.createAppointment(a1)
service.createAppointment(a2)
service.createAppointment(a3)
service.createAppointment(a4)
service.createAppointment(a5)
service.listAll()