# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBHSWe7s9bsmOm6iK2D6kHa_-b8__WLZ

# Projeto Final - Arquitetura de Software - Grau Tec.
---
#### By: José Anderson P. de Alencar
"""

from datetime import date

# Model
class Student:
  def __init__(self, id:str, name:str, cpf:str):
    self.id = id
    self.name = name
    self.cpf = cpf

class Course:
  def __init__(self, id:str, name:str, hourDuration:int):
    self.id = id
    self.name = name
    self.hourDuration = hourDuration

class Registration:
  def __init__(self, id:str, student:Student, course:Course):
    self.id = id
    self.student = student
    self.course = course
    self.payment = False

  def doPay(self):
    self.payment = True

class PaymentService:
  def pay(self, registration:Registration): pass

class CreditPaymentService(PaymentService):
  def pay(self, registration:Registration):
    registration.doPay()
    print('\tPayment by Credit Card.')

class PixPaymentService(PaymentService):
  def pay(self, registration:Registration):
    registration.doPay()
    print('\tPayment by Pix.')
    
class Boleto(PaymentService):
  def pay(self, registration:Registration):
    registration.doPay()
    print('\tPayment by Boleto.')

# Service
class StudentService:
  def __init__(self, students:list):
    self.students = students

  def addStudent(self, student:Student):
    self.students.append(student)

  def searchById(self, id:str):
    for index, s in enumerate(self.students):
      if (s.id == id): return s, index
    return -1

  def remove(self, id:str):
    student = self.searchById(id)
    if(student == -1): return -1
    self.students.pop(student[1])
    return 0

class CourseService:
  def __init__(self, courses:list):
    self.courses = courses

  def addCourse(self, course:Course):
    self.courses.append(course)

  def searchById(self, id:str):
    for index, c in enumerate(self.courses):
      if (c.id == id): return c, index
    return -1

  def remove(self, id:str):
    course = self.searchById(id)
    if(course == -1): return -1
    self.courses.pop(course[1])
    return 0

class RegistrationService:
  def __init__(self, registrations:list, serviceS:StudentService, serviceC:CourseService):
    self.registrations = registrations
    self.serviceS = serviceS
    self.serviceC = serviceC

  def addRegistration(self, registration:Registration):
    self.registrations.append(registration)

  def searchById(self, id:str):
    for index, r in enumerate(self.registrations):
      if(r.id == id): return r, index
    return -1

  def remove(self, id:str):
    registration = self.searchById(id)
    if(registration == -1): return -1
    self.registrations.pop(registration[1])
    return 0

  def payment(self, id:str, pay:PaymentService):
    registration = self.searchById(id)
    if(registration == -1): return -1
    pay.pay(registration[0])

class NotificationService:
  def sendNotification(self, message:str):
    return message

# Controller
class StudentController:
  def __init__(self, service:StudentService):
    self.service = service

  def main(self):
    while True:
      print("\n########### STUDENT MENU ############")
      print('1 - Add Student')
      print('2 - Search Student by ID')
      print('3 - Remove Student')
      print('4 - Exit')
      option = input('Choice: ')
      match option:
        case "1": self.add()
        case "2": self.search()
        case "3": self.remove()
        case "4":
          print('Exiting...')
          break
        case _: print('Invalid Option!')

  def add(self):
    id = input("Enter ID: ")
    name = input("Enter Name: ")
    cpf = input('Enter CPF: ')
    student = Student(id, name, cpf)
    self.service.addStudent(student)
    print(f'Student {name} Sucessfully Added!')

  def search(self):
    id = input('Enter ID: ')
    student = self.service.searchById(id)
    if(student == -1): print('No Student Found!')
    else:
      print("===================================")
      print("ID: ", student[0].id)
      print("NAME: ", student[0].name)
      print("CPF: ", student[0].cpf)
      print("===================================")

  def remove(self):
    id = input('Enter ID: ')
    student = self.service.remove(id)
    if(student == -1): print('No Student Found with this ID!')
    else: print('Student Successfully Removed!')

class CourseController:
  def __init__(self, service:CourseService):
    self.service = service

  def main(self):
    while True:
      print("\n########### COURSE MENU ############")
      print('1 - Add Course')
      print('2 - Search Course by ID')
      print('3 - Remove Course')
      print('4 - Exit')
      option = input('Choice: ')
      match option:
        case "1": self.add()
        case "2": self.search()
        case "3": self.remove()
        case "4":
          print('Exiting...')
          break
        case _: print('Invalid Option!')

  def add(self):
    id = input("Enter ID: ")
    name = input("Enter Name: ")
    hour = int(input('Enter Hour Duration: '))
    course = Course(id, name, hour)
    self.service.addCourse(course)
    print(f'Course {name} Sucessfully Added!')

  def search(self):
    id = input('Enter ID: ')
    course = self.service.searchById(id)
    if(course == -1): print('No Course Found!')
    else:
      print("===================================")
      print("ID:", course[0].id)
      print("NAME:", course[0].name)
      print("DURATION:", course[0].hourDuration, "hrs")
      print("===================================")

  def remove(self):
    id = input('Enter ID: ')
    course = self.service.remove(id)
    if(course == -1): print('No Course Found with this ID!')
    else: print('Course Successfully Removed!')

class registrationController:
  def __init__(self, service:RegistrationService):
    self.service = service

  def main(self):
    while True:
      print("\n########### REGISTRATION MENU ############")
      print('1 - Add Registration')
      print('2 - Search Registration by ID')
      print('3 - Remove Registration')
      print('4 - Pay Registration')
      print('5 - Exit')
      option = input('Choice: ')
      match option:
        case "1": self.add()
        case "2": self.search()
        case "3": self.remove()
        case "4": self.pay()
        case "5":
          print('Exiting...')
          break
        case _: print('Invalid Option!')

  def add(self):
    id = input("Enter ID: ")
    idStudent = input("Enter Student ID: ")
    student = self.service.serviceS.searchById(idStudent)
    if(student == -1):
      print('Student Not Found!')
      return
    idCourse = input("Enter Course ID: ")
    course = self.service.serviceC.searchById(idCourse)
    if(course == -1):
      print('Course Not Found!')
      return
    registration = Registration(id, student[0], course[0])
    self.service.addRegistration(registration)
    print(f'Registration {id} Sucessfully Added!')

  def search(self):
    id = input('Enter ID: ')
    registration = self.service.searchById(id)
    if(registration == -1): print('No Registration Found!')
    else:
      print("===================================")
      print("ID:", registration[0].id)
      print("STUDENT:", registration[0].student.name)
      print("COURSE:", registration[0].course.name)
      print("PAYMENT:", registration[0].payment)
      print("===================================")

  def remove(self):
    id = input('Enter ID: ')
    registration = self.service.remove(id)
    if(registration == -1): print('No Registration Found with this ID!')
    else: print('Registration Successfully Removed!')

  def pay(self):
    id = input('Enter Registration ID: ')
    test = self.service.searchById(id)
    if(test == -1): 
      print('No Registration Found!')
      return
    print('\t1 - Pay with Credit Card.')
    print('\t2 - Pay with PIX.')
    print('\t3 - Pay with Boleto.')
    option = input('\tChoice:')
    match option:
      case "1": self.service.payment(id, CreditPaymentService())
      case "2": self.service.payment(id, PixPaymentService())
      case '3': self.service.payment(id, Boleto())
      case _: print('\tInvalid Option!')

s = Student('S001','Anderson','1111111')
students = [s]
c = Course('C001','POO',45)
courses = [c]
registrations = []
studentService = StudentService(students)
courseService = CourseService(courses)
registrationService = RegistrationService(registrations, studentService, courseService)
studentControl = StudentController(studentService)
courseControl = CourseController(courseService)
registrationControl = registrationController(registrationService)

while True:
  print("\n########### MAIN MENU ############")
  print('1 - Students Menu')
  print('2 - Course Menu')
  print('3 - Registration Menu')
  print('4 - Exit')
  option = input('Choice: ')
  match option:
    case '1': studentControl.main()
    case '2': courseControl.main()
    case '3': registrationControl.main()
    case '4':
      print('Exiting...')
      break
    case _: print('Invalid Option!')