# -*- coding: utf-8 -*-
"""Atividade01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-L60NMKrqq6dDMul3oA9QT9iggkptRFz
"""

#===========================================
# SINGLE RESPONSIBILITY PRINCIPLE - (S)OLID
#===========================================
# - Wrong Way
class User:
  def __init__(self, name:str, email:str):
    self.name = name
    self.email = email

  def saveInDB(self):
    print('Saving in Database')

  def sendWelcomingEmail(self):
    print('Sending Welcome\'s Email')

  def generateReport(self):
    print('Generating User\'s Report')

# - Right Way
class UserModel:
  def __init__(self, name:str, email:str):
    self.name = name
    self.email = email

class UserRepository:
  def saveinDB(self, user:UserModel):
    print(f'Saving User {user.name} in Database')

class EmailService:
  def sendWelcomingEmail(self, user:UserModel):
    print(f'Sending a Welcome Email to {user.email}')

class ReportService:
  def generateReport(self, user:UserModel):
    print(f'Generating {user.name}\'s Report')

user = User('Andy', 'andyandy@email.com')
ur = UserRepository()
ur.saveinDB(user)
es = EmailService()
es.sendWelcomingEmail(user)
rs = ReportService()
rs.generateReport(user)

#===============================
# OPEN/CLOSE PRINCIPLE - S(O)LID
#===============================
# - Wrong Way
class Notification:
  def __init__(self, message:str):
    self.message = message

  def send(self, type:str):
    if(type == 'email'):
      print(f'Sending Email: {self.message}')
    elif(type == 'sms'):
      print(f'Sending SMS: {self.message}')
    elif(type == 'whatsapp'):
      print(f'Sending Whatsapp: {self.message}')
    elif(type == 'telegram'):
      print(f'Sending Telegram: {self.message}')

# - Right Way
class Channel:
  def send(self, notification:str): pass

class Email(Channel):
  def send(self, notification:str):
    print(f'Sending Email: {notification}')

class Sms(Channel):
  def send(self, notification:str):
    print(f'Sending SMS: {notification}')

class Whatsapp(Channel):
  def send(self, notification:str):
    print(f'Sending Whatsapp: {notification}')

class Telegram(Channel):
  def send(self, notification:str):
    print(f'Sending Telegram: {notification}')

class NotificationService:
  def send(self, channel:Channel, message:str):
    channel.send(message)

m = 'Congratulations!'
mw = Whatsapp()
ms = Sms()
mt = Telegram()
me = Email()
ns = NotificationService()
ns.send(mw, m)
ns.send(ms, m)
ns.send(mt, m)
ns.send(me, m)

#========================================
# LISKOV SUBSTITUTION PRINCIPLE - SO(L)ID
#========================================
# - Wrong Way
class Payment:
  def pay(self, value:float):
    print(f'Paying R$ {value:.2f}')

class FreePayment(Payment):
  def pay(self, value:float):
    raise Exception('No need to pay!')

# - Right Way
class PaymentService:
  def pay(self, value:float): pass

class NormalPaymentService(PaymentService):
  def pay(self, value:float):
    print(f'Paying R$ {value:.2f}')

class FreePaymentService(PaymentService):
  def pay(self, value:float):
    print(f'Paying R$ 0.00 (Exempt - R$ {value:.2f})')

class Processing:
  @staticmethod
  def doPay(payment:PaymentService, value:float):
    payment.pay(value)

p1 = NormalPaymentService()
p2 = FreePaymentService()
Processing.doPay(p1, 150.50)
Processing.doPay(p2, 200.85)