# -*- coding: utf-8 -*-
"""Atividade02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enpUotY-haoXONFnWC83aDxhcx7gWokL
"""

class PedidoW:

    def __init__(self, valor):
        self.valor = valor

    def calcular_frete(self, tipo):
        if tipo == "normal":
            return 20
        elif tipo == "expressa":
            return 40

    def pagar_cartao(self):
        print("Pagamento com cartão")

    def pagar_pix(self):
        print("Pagamento com pix")

    def emitir_nota(self):
        print("Nota fiscal emitida")


class PedidoGratisW(PedidoW):

    def calcular_frete(self, tipo):
        raise Exception("Pedido grátis não tem frete")

from typing_extensions import override
class RequestModel:
  def __init__(self, value:float):
    self.value = value

class Shipping:
  def __init__(self, value:float):
    self.value = value

class NormalShipping(Shipping):
  def __init__(self):
    super().__init__(20)

class ExpressShipping(Shipping):
  def __init__(self):
    super().__init__(40)

class RequestService:
  def calculateShipping(self, shipping:Shipping):
    return shipping.value

  def printInvoice(self):
    print('Printing Invoice.')

class FreeRequestService(RequestService):
  def calculateShipping(self, shipping: Shipping):
    return 'Free Resquest doesn\'t have Shipping Price'

class Payment:
  @staticmethod
  def payCredit():
    print('Pay with Credit Card.')

  @staticmethod
  def payPix():
    print('Pay with PIX.')

